name: Deploy portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Portfolio bauen
        run: npm run build

      - name: Build auf Netcup übertragen
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: dist/portfolio/browser/*
          target: franziska-kalloch.de/httpdocs
          strip_components: 3
          overwrite: true
